config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name,:address,:password,presence: true
    validates :email,presence: true,uniqueness: true
    has_many :posts, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = PostsService.index
    PostMailer.post_list(current_user.email,@posts).deliver_now
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = PostsService.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    params[:post][:user_id] = current_user.id
    @post = PostsService.createPost(post_params)

    respond_to do |format|
      if @post.save
        format.js
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.js
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.js
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    PostsService.delete(params[:id])

    respond_to do |format|
      format.js
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description,:user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to posts_path
      else
        flash.now[:alert] = "Logged in failed"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil 
      redirect_to root_url
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = UsersService.index
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = UsersService.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = UsersService.createUser(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.user_send(@user).deliver_now
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    UsersService.delete(params[:id])

    respond_to do |format|
      UserMailer.user_delete(@user).deliver_now
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :address, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<div class="container ">
    <h1 class="display-4 text-center mt-5">Welcome Main Page</h1>
</div>

app/views/posts/_error.html.erb
<% if post.errors.any? %>
  <div id="error_explanation">
    <h6 class="text-danger"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h6>
    <% post.errors.each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= error.full_message %></strong> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post,local: false) do |form| %>
  <div class="modal-body">
  <div id="errorArea">
  </div>
  <div class="form-group mt-3">
    <%= form.label :title %>
    <%= form.text_field :title ,class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :description %>
    <%= form.text_field :description ,class: 'form-control' %>
  </div>
      <div class="modal-footer">
        <%= form.submit class: 'btn btn-primary btn-m mt-5 mb-5' %>
        <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>
      
      </div>
  
<% end %>

app/views/posts/_post_row.html.erb
<tr id="postRow_<%= post.id %>">
  <td><%= post.title %></td>
  <td><%= post.description %></td>
  <td>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Action
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><%= link_to 'Show', post ,class: 'dropdown-item',
        data: { bs_toggle: 'modal',bs_target: '#showPostModal', remote: true} %></li>
        <li><%= link_to 'Edit', edit_post_path(post) ,class: 'dropdown-item' ,
        data: { bs_toggle: 'modal',bs_target: '#editPostModal', remote: true}%></li>
        <li><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'dropdown-item' , remote: true %></li>
    </ul>
    </div>
  </td>
</tr>

app/views/posts/_show.html.erb
<div class="modal-body">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <strong>Title:</strong>
            <%= post.title %>
        </p>

        <p>
            <strong>Description:</strong>
            <%= post.description %>
        </p>
        </div>
    </div>
    </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>  
</div>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
    $("#errorArea").html("<%= escape_javascript render('error', post: @post)%>");
<% else %>
    $("#postsTable").prepend("<%= escape_javascript render('post_row', post: @post)%>")
    $(".close-modal").click();
<% end %>

app/views/posts/destroy.js.erb
$("#postRow_<%= @post.id %>").remove();

app/views/posts/edit.js.erb
$("#editPostForm").html("<%= escape_javascript render('form', post: @post)%>");

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-md-auto">
      <h1 class="display-4">Post List</h1>
      <br>
      <div class="row">
        <div class="col-lg-10 mx-md-auto">
          <%= link_to 'Create Post', new_post_path ,class: 'btn btn-primary btn-sm mb-3' ,
          data: { bs_toggle: 'modal', bs_target: '#newPostModal', remote:true}%>
        </div>
        <div class="col-lg-2 mx-md-auto">
          <%= link_to "Send List", posts_path , class: "btn btn-primary btn-sm" %>
        </div>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Operation</th>
          </tr>
        </thead>

        <tbody id="postsTable">
          <% @posts.each do |post| %>
            <%= render 'post_row' , post: post %>
          <% end %>
        </tbody>
      </table>
         
    </div>
  </div>
</div>

<div class="modal fade" id="newPostModal" tabindex="-1" aria-labelledby="newPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPostModalLabel">Create New Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newPostForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editPostModal" tabindex="-1" aria-labelledby="editPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editPostModalLabel">Edit Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="editPostForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="showPostModal" tabindex="-1" aria-labelledby="showPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showPostModalLabel">Post Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="showPostDetails">
      </div>
    </div>
  </div>
</div>

app/views/posts/new.js.erb
$("#newPostForm").html("<%= escape_javascript render('form', post: @post)%>");

app/views/posts/show.js.erb
$("#showPostDetails").html("<%= escape_javascript render('show', post: @post)%>");

app/views/posts/update.js.erb
<% if @post.errors.any? %>
    $("#errorArea").html("<%= escape_javascript render('error', post: @post)%>");
<% else %>
    $("#postRow_<%= @post.id %>").replaceWith("<%= escape_javascript render('post_row', post: @post)%>")
    $(".close-modal").click();
<% end %>

app/views/shared/_header.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-2">
            <div class="row">
                <div class="col">
                    <p><%= link_to "Users" , users_path %></p>
                </div>
                <div class="col">
                    <p><%= link_to "Posts" , posts_path %></p>
                </div>   
            </div>
        </div>
        <div class="col-10">
          <% if current_user %>
            <div class="row">
              <div class="col-4">
                <p><strong>Logged in as :</strong> <%= current_user.email %></p>
              </div>
              <div class="col-2">
              <%= button_to "logout" , logout_path, method: :delete ,class: 'form-control btn-danger btn-sm ml-3'%>
              </div>
            </div>
          <% else %>
            <%= link_to 'Log in', login_path ,class: 'btn btn-primary' %>
          <% end %>
        </div>
    </div>
</div>

app/views/users/_error.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h6 class="text-danger"><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h6>
    <% user.errors.each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= error.full_message %></strong> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user,local: false) do |form| %>
  <div class="modal-body">
  <div id="errorArea">
  </div>
  <div class="form-group mt-3">
    <%= form.label :name %>
    <%= form.text_field :name ,class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :email %>
    <%= form.text_field :email ,class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :address %>
    <%= form.text_field :address ,class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= form.label :password %>
    <%= form.password_field :password ,class: 'form-control' %>
  </div>
  </div>
      <div class="modal-footer">
        <%= form.submit class: 'btn btn-primary btn-m mt-5 mb-5' %>
        <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>
      
      </div>
  
<% end %>

app/views/users/_show.html.erb
<div class="modal-body">
    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <strong>Name:</strong>
            <%= user.name %>
        </p>

        <p>
            <strong>Email:</strong>
            <%= user.email %>
        </p>

        <p>
            <strong>Address:</strong>
            <%= user.address %>
        </p>

        <p>
            <strong>Password:</strong>
            <%= user.password %>
        </p>
        </div>
    </div>
    </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>  
</div>

app/views/users/_user_row.html.erb
<tr id="userRow_<%= user.id %>">
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.address %></td>
  <td>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Action
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><%= link_to 'Show', user ,class: 'dropdown-item',
        data: { bs_toggle: 'modal',bs_target: '#showUserModal', remote: true} %></li>
        <li><%= link_to 'Edit', edit_user_path(user) ,class: 'dropdown-item' ,
        data: { bs_toggle: 'modal',bs_target: '#editUserModal', remote: true}%></li>
        <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'dropdown-item' , remote: true %></li>
    </ul>
    </div>
  </td>
</tr>

app/views/users/create.js.erb
<% if @user.errors.any? %>
    $("#errorArea").html("<%= escape_javascript render('error', user: @user)%>");
<% else %>
    $("#usersTable").prepend("<%= escape_javascript render('user_row', user: @user)%>")
    $(".close-modal").click();
<% end %>

app/views/users/destroy.js.erb
$("#userRow_<%= @user.id %>").remove();

app/views/users/edit.js.erb
$("#editUserForm").html("<%= escape_javascript render('form', user: @user)%>");

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-md-auto">
      <h1 class="display-4">User List</h1>
      <br>

      <%= link_to 'Create User', new_user_path ,class: 'btn btn-primary btn-sm mb-3' ,
      data: { bs_toggle: 'modal', bs_target: '#newUserModal', remote:true}%>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th>Operation</th>
          </tr>
        </thead>

        <tbody id="usersTable">
          <% @users.each do |user| %>
            <%= render 'user_row' , user: user %>
          <% end %>
        </tbody>
      </table>
        <%= link_to '<< Back', root_path ,class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
</div>

<div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">Create New User</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newUserForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editUserModalLabel">Edit User</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="editUserForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="showUserModal" tabindex="-1" aria-labelledby="showUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showUserModalLabel">User Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="showUserDetails">
      </div>
    </div>
  </div>
</div>

app/views/users/new.js.erb
$("#newUserForm").html("<%= escape_javascript render('form', user: @user)%>");

app/views/users/show.js.erb
$("#showUserDetails").html("<%= escape_javascript render('show', user: @user)%>");

app/views/users/update.js.erb
<% if @user.errors.any? %>
    $("#errorArea").html("<%= escape_javascript render('error', user: @user)%>");
<% else %>
    $("#userRow_<%= @user.id %>").replaceWith("<%= escape_javascript render('user_row', user: @user)%>")
    $(".close-modal").click();
<% end %>